FROM php:7.0-cli

# install dependences
RUN apt-get update && apt-get install -y libcurl4-gnutls-dev zlib1g-dev git
RUN docker-php-ext-configure curl --with-curl
RUN docker-php-ext-install -j$(nproc) curl zip
