FROM php:8.3-cli

# install dependencies
RUN apt-get update && apt-get install -y libcurl4-gnutls-dev zlib1g-dev git ffmpeg
RUN docker-php-ext-configure curl --with-curl
RUN docker-php-ext-install -j$(nproc) curl zip
